"""PCM v5 — Statistical-attractor heads.

When a dynamical system has Lyapunov exponent λ\\* > 0, F60 showed
that PCM v4 ``PhysicsCook`` accuracy degrades exponentially past
the Lyapunov horizon ``K\\* ~ 1/λ\\*`` regardless of how good the
1-step head is. The procedural simulation is futile: small per-
step errors are amplified to system size.

This module provides the architectural counterpart for the chaotic
regime: instead of predicting a *trajectory*, predict the
*distribution of outcomes*. This mirrors the cognitive pattern of
"I know how three-body collisions usually end (one body ejects,
the binary keeps most of the energy)" without claiming to predict
which body or exactly when.

The dual-process picture this produces is the cleanest version of
the System 1 / System 2 split we have so far:

* **System 1 (`AttractorHead`)** — one shot, ``O(1)`` cost,
  predicts statistical descriptors of long-horizon behaviour.
  Used when ``K_target > K*`` (chaotic horizon exceeded).
* **System 2 (`PhysicsCook`)** — iterative, ``O(K)`` cost,
  predicts the actual trajectory pointwise. Used when
  ``K_target ≤ K*`` (still inside the predictability horizon).
* **`HybridPhysicsDispatcher`** — picks between them given the
  caller's ``K_target`` and the system's ``K_star``.

Falsifiable invariants tested by ``experiments/three_body_attractor_poc.py``:

* **A1** — AttractorHead exceeds the random-3-class baseline on
  *which body ejects* (``> 0.40`` vs ``0.33`` chance).
* **A2** — AttractorHead beats a constant-mean predictor on the
  ``log(time_to_ejection)`` regression (R² > 0).
* **A3** — Hybrid dispatcher beats both cook-only (which fails on
  long horizons) and attractor-only (which can't do short
  horizons) on the per-K_target Wasserstein-1 distance to the
  empirical outcome distribution.
* **A4** — AttractorHead 1-shot energy-partition KL beats a
  uniform-distribution baseline.

The design is N-body-agnostic: outputs scale with ``n_bodies``,
so the same head can be re-trained on N=4, N=5, ... systems.

See ``docs/PCM_V5_ATTRACTOR_DESIGN.md`` for theory and broader
positioning vs world models / Causal-JEPA.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import torch
import torch.nn as nn
import torch.nn.functional as F


__all__ = [
    "AttractorHead",
    "AttractorOutput",
    "AttractorTargets",
    "attractor_loss",
    "HybridPhysicsDispatcher",
    "HybridDecision",
]


# ─────────────────────────────────────────────────────────────────
# AttractorHead — predicts outcome distribution descriptors
# ─────────────────────────────────────────────────────────────────


@dataclass
class AttractorOutput:
    """Outputs of :class:`AttractorHead.forward`.

    Each tensor is leading-batched (``B = batch size``):

    * ``escape_logits`` — ``(B, n_bodies)``, unnormalised logits
      over which body is the first to escape the system.
    * ``log_escape_time`` — ``(B,)``, predicted ``log(t_eject)``
      where ``t_eject`` is the number of steps until the ejection
      criterion is met.
    * ``energy_logits`` — ``(B, n_bodies)``, unnormalised logits
      over the final energy fraction held by each body (softmax
      gives a probability simplex).
    * ``mean_final_state`` — ``(B, state_dim)``, expected long-
      horizon state. Used for A4 / for graceful fallback when the
      caller wanted a state but the system is past K*.
    * ``log_std_final_state`` — ``(B, state_dim)``, predicted
      log-standard-deviation of long-horizon state. Calibrated
      uncertainty in the regime where exact prediction is
      impossible.
    """

    escape_logits: torch.Tensor
    log_escape_time: torch.Tensor
    energy_logits: torch.Tensor
    mean_final_state: torch.Tensor
    log_std_final_state: torch.Tensor


@dataclass
class AttractorTargets:
    """Ground-truth labels for training :class:`AttractorHead`.

    Generated by ensemble-rolling the ground-truth integrator on a
    large number of perturbed initial conditions and recording
    statistics; see ``experiments/three_body_attractor_poc.py``
    for the canonical pipeline.

    * ``escape_label`` — ``(B,)`` ``int64`` body index.
    * ``log_escape_time`` — ``(B,)`` ``float``.
    * ``energy_target`` — ``(B, n_bodies)`` non-negative,
      sum-to-one (probability simplex).
    * ``mean_final_state`` — ``(B, state_dim)``.
    * ``std_final_state`` — ``(B, state_dim)``, must be > 0.
    """

    escape_label: torch.Tensor
    log_escape_time: torch.Tensor
    energy_target: torch.Tensor
    mean_final_state: torch.Tensor
    std_final_state: torch.Tensor


class AttractorHead(nn.Module):
    """Predicts statistical descriptors of long-horizon outcomes
    from a single state, in one shot.

    Architecturally this is a wide MLP with three small heads:

    * a categorical head (escape body),
    * a scalar regressor (log time to ejection),
    * a categorical head (energy partition simplex),
    * a Gaussian regressor (state distribution: mean + log-σ).

    Note that the head does **not** consume the time horizon
    ``K``; in the chaotic regime past ``K*``, the outcome
    distribution is ``K``-invariant once the system has settled
    into its attractor. If you want ``K``-conditioned behaviour
    use ``HybridPhysicsDispatcher`` to switch to cook for
    ``K ≤ K*``.

    Args:
        state_dim: dimensionality of the input state vector.
        n_bodies: number of bodies the system contains. Output
            shapes scale with this.
        hidden: trunk MLP hidden size. Default 256.
        depth: number of trunk MLP hidden layers. Default 3.
    """

    def __init__(
        self,
        state_dim: int,
        n_bodies: int,
        *,
        hidden: int = 256,
        depth: int = 3,
    ) -> None:
        super().__init__()
        self.state_dim = state_dim
        self.n_bodies = n_bodies

        layers: list[nn.Module] = [nn.Linear(state_dim, hidden), nn.SiLU()]
        for _ in range(depth - 1):
            layers.extend([nn.Linear(hidden, hidden), nn.SiLU()])
        self.trunk = nn.Sequential(*layers)
        self.escape = nn.Linear(hidden, n_bodies)
        self.log_time = nn.Linear(hidden, 1)
        self.energy = nn.Linear(hidden, n_bodies)
        self.mean = nn.Linear(hidden, state_dim)
        self.log_std = nn.Linear(hidden, state_dim)

    def forward(self, state: torch.Tensor) -> AttractorOutput:
        h = self.trunk(state)
        log_std = self.log_std(h)
        # Clamp log-σ so the network can't trivially make all
        # losses go to zero by predicting absurdly large variance.
        log_std = torch.clamp(log_std, min=-3.0, max=5.0)
        return AttractorOutput(
            escape_logits=self.escape(h),
            log_escape_time=self.log_time(h).squeeze(-1),
            energy_logits=self.energy(h),
            mean_final_state=self.mean(h),
            log_std_final_state=log_std,
        )


def attractor_loss(
    pred: AttractorOutput,
    target: AttractorTargets,
    *,
    weight_escape: float = 1.0,
    weight_time: float = 0.5,
    weight_energy: float = 1.0,
    weight_state: float = 1.0,
) -> tuple[torch.Tensor, dict]:
    """Composite loss for :class:`AttractorHead`.

    Components, in order matching the dataclass:

    * **escape**: cross-entropy over which body ejects.
    * **time**: MSE on ``log(escape_time)``. Working in log space
      compresses the long tail of close-encounter scattering events
      and stabilises training.
    * **energy**: KL divergence from predicted energy simplex to
      the empirical simplex, treating the simplex as a soft
      categorical (target probabilities).
    * **state**: Gaussian negative-log-likelihood with predicted
      mean and predicted log-σ. Encourages the head to be
      under-confident in chaotic regimes (calibrated uncertainty)
      while still pointing at the ensemble mean.

    Returns ``(total_loss, components_dict)`` for logging. All
    components are means over the batch dimension.
    """
    # Escape body classifier
    loss_escape = F.cross_entropy(pred.escape_logits, target.escape_label)
    # Log-time regression
    loss_time = F.mse_loss(pred.log_escape_time, target.log_escape_time)
    # Energy simplex KL: treat energy_target as soft probabilities
    pred_logp = F.log_softmax(pred.energy_logits, dim=-1)
    # KL(target || pred) = Σ target * (log target - log pred)
    eps = 1e-8
    log_target = torch.log(target.energy_target + eps)
    loss_energy = (target.energy_target * (log_target - pred_logp)).sum(dim=-1).mean()
    # Gaussian NLL for the final-state mean+std
    var = torch.exp(2.0 * pred.log_std_final_state)
    sq_err = (pred.mean_final_state - target.mean_final_state).pow(2)
    loss_state = (
        0.5 * (sq_err / var + 2.0 * pred.log_std_final_state)
    ).mean()

    total = (
        weight_escape * loss_escape
        + weight_time * loss_time
        + weight_energy * loss_energy
        + weight_state * loss_state
    )
    return total, {
        "loss_escape": float(loss_escape.detach().item()),
        "loss_time": float(loss_time.detach().item()),
        "loss_energy": float(loss_energy.detach().item()),
        "loss_state": float(loss_state.detach().item()),
        "loss_total": float(total.detach().item()),
    }


# ─────────────────────────────────────────────────────────────────
# Hybrid dispatcher — System 1 vs System 2 routing
# ─────────────────────────────────────────────────────────────────


@dataclass
class HybridDecision:
    """The output of :class:`HybridPhysicsDispatcher.predict`.

    Exactly one of ``cook_state`` and ``attractor`` is populated.
    """

    used: str  # "cook" | "attractor"
    K_target: int
    K_star: int
    cook_state: torch.Tensor | None
    attractor: AttractorOutput | None


class HybridPhysicsDispatcher:
    """Routes a physics prediction request between cook (System 2)
    and attractor (System 1) based on the predictability horizon.

    The decision rule is::

        used = "cook"      if K_target <= K_star
        used = "attractor" if K_target > K_star

    Beyond ``K_star`` the cook's per-step error is amplified by
    ``exp(λ\\* K)`` to system size (F60); within it cook is
    pointwise accurate. ``K_star`` should be calibrated from the
    system's ground-truth Lyapunov exponent — the
    ``GT_lyapunov_max_window_slope`` field saved by
    ``experiments/three_body_poc.py`` is the canonical source.

    Args:
        cook: anything callable as ``(state, K) -> (final_state, _)``.
            We only consume the first element. ``PhysicsCook`` from
            ``pcm.physics`` matches this signature.
        attractor: an :class:`AttractorHead` instance.
        K_star: the predictability horizon (``int`` steps).
    """

    def __init__(
        self,
        *,
        cook: Callable[..., tuple[torch.Tensor, object]],
        attractor: AttractorHead,
        K_star: int,
    ) -> None:
        self.cook = cook
        self.attractor = attractor
        self.K_star = K_star

    def predict(
        self, state: torch.Tensor, *, K_target: int,
    ) -> HybridDecision:
        if K_target <= self.K_star:
            cook_state, _ = self.cook(state, K=K_target)
            return HybridDecision(
                used="cook",
                K_target=K_target,
                K_star=self.K_star,
                cook_state=cook_state,
                attractor=None,
            )
        attractor_out = self.attractor(state)
        return HybridDecision(
            used="attractor",
            K_target=K_target,
            K_star=self.K_star,
            cook_state=None,
            attractor=attractor_out,
        )

    def __repr__(self) -> str:
        return (
            f"HybridPhysicsDispatcher(K_star={self.K_star}, "
            f"cook={type(self.cook).__name__}, "
            f"attractor=AttractorHead(state_dim="
            f"{self.attractor.state_dim}, "
            f"n_bodies={self.attractor.n_bodies}))"
        )
